language: ruby
rvm:
- 2.1

sudo: false

after_success:
- find . -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://petercooperblockparty.com/petercooperblockparty.com/public/2016/{}
  \;
